# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160721_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='theme',
            field=models.CharField(default='tarzan', max_length=250),
            preserve_default=False,
        ),
    ]
