# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventspage_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspage',
            name='theme',
        ),
    ]
