# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupage',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='menupage',
            name='image',
        ),
    ]
