# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160721_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'person', wagtail.wagtailcore.blocks.StreamBlock([(b'first_name', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
