# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 13:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menupage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'dish', wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'demo', wagtail.wagtailimages.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
